### ISSUE TITLE
Fatal error at retrieving cookies

### ISSUE THREAD

**Issue by Evernow** [Megalan/PatreonDownloader#11] opened 2020-07-04 04:23 UTC
Hello there!

Before anything thank you for making such a utility! 

Sadly when attempting to run it throws a fatal error when retrieving the cookies

[daniel@daniel-pc ~]$ /home/daniel/net3.1-linux-x64-release/PatreonDownloader.App --creator LeeandLie --descriptions --embeds --campaign-images --json --verbose
2020-07-04 00:22:47.9929 INFO Retrieving cookies...
2020-07-04 00:22:48.0217 DEBUG Calling login check
2020-07-04 00:22:48.0298 DEBUG Retrieving browser
2020-07-04 00:22:48.0298 DEBUG Downloading browser
2020-07-04 00:22:48.0377 DEBUG Launching browser
2020-07-04 00:22:48.3404 DEBUG Opening new page
2020-07-04 00:22:48.4574 DEBUG Creating IWebBrowser
2020-07-04 00:22:48.4809 DEBUG Checking login status
2020-07-04 00:22:49.3793 DEBUG We are NOT logged in, opening login page
2020-07-04 00:22:49.3793 DEBUG Puppeteer is in headless mode, restarting in full mode
2020-07-04 00:22:50.4189 DEBUG Downloading browser
2020-07-04 00:22:50.4189 DEBUG Launching browser
2020-07-04 00:22:50.6886 DEBUG Opening new page
2020-07-04 00:22:50.7399 DEBUG Creating IWebBrowser
2020-07-04 00:22:56.3797 FATAL Fatal error, application will be closed: PuppeteerSharp.TargetClosedException: Target closed (Session closed)
   at PuppeteerSharp.Page.WaitForRequestAsync(Func`2 predicate, WaitForOptions options)
   at PatreonDownloader.PuppeteerEngine.Wrappers.Browser.WebPage.WaitForRequestAsync(Func`2 predicate, WaitForOptions options) in E:\Sources\BigProjects\PatreonDownloader\PatreonDownloader.PuppeteerEngine\Wrappers\Browser\WebPage.cs:line 56
   at PatreonDownloader.PuppeteerEngine.PuppeteerCookieRetriever.Login() in E:\Sources\BigProjects\PatreonDownloader\PatreonDownloader.PuppeteerEngine\PuppeteerCookieRetriever.cs:line 66
   at PatreonDownloader.PuppeteerEngine.PuppeteerCookieRetriever.RetrieveCookies() in E:\Sources\BigProjects\PatreonDownloader\PatreonDownloader.PuppeteerEngine\PuppeteerCookieRetriever.cs:line 93
   at PatreonDownloader.App.Program.RunPatreonDownloader(String creatorName, Boolean headlessBrowser, PatreonDownloaderSettings settings) in E:\Sources\BigProjects\PatreonDownloader\PatreonDownloader.App\Program.cs:line 117
   at PatreonDownloader.App.Program.Main(String[] args) in E:\Sources\BigProjects\PatreonDownloader\PatreonDownloader.App\Program.cs:line 58

I am not sure if I was to provide the cookie in a file somewhere, the browser opens, loads patreon then closes a second afterwards.

On Manjaro, the browser was not opening at all with firejail enabled, disabled firejail but sadly didn't get much further.

**Comment by Megalan** [comment] 2020-07-04 11:58
You do not need to provide cookies manually.

Unfortunately I cannot reproduce this issue on a clean install of Manjaro 20.0.3. Neither I've been able to do it with a fresh install of firejail on top of it.

The error message says that tab or browser process was killed, so I guess you have some other software which doesn't let the browser do its job.

I am closing this issue for now as this doesn't look like a problem with app itself. Feel free to leave a comment with a solution if you'll be able to solve this problem.

**Closed by Megalan** 2020-07-04 11:58 UTC

**Comment by Evernow** [comment] 2020-07-04 13:05
@Megalan Upon further testing, me building it allowed it to work, the prebuild ( https://github.com/Megalan/PatreonDownloader/releases/tag/0.9.1.1 ) was causing the issue.

**Comment by Megalan** [comment] 2020-07-04 13:36
This is a really strange issue because this build was working fine all linux distros I tested it on, but I'm glad it works fine for you now.
